#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid
jupyter labextension install jupyterlab-plotly@4.8.1
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.8.1
jupyter labextension install @jupyter-widgets/jupyterlab-manager